### ISSUE TITLE
Initializing the Database

### ISSUE THREAD

**Issue by Mehrdadmaskull** [Data-Boom/SOEN490#114]
As a Developer, I would like to have a database server setup, initialized with tables, and queries working.

**Description:**
The purpose of this userstory is to find a place to create the database server, connect to it, initialize it with the database tables, and create queries to fetch certain data.

**Tasks Involved:**

- [x] Research into where to create the database
- [x] Create the database
- [x] Connect to it through the website
- [x] Initialize the tables
- [x] Create the queries

**Acceptance Criteria**

- To accept this userstory, there must be an existing database server with a database initialized with tables (Refer to the ER diagram) and queries to retrieve datasets.

**Story Point** - 5
**RIsk** - High
**Priority** - High

**USE THE RIGHT LABELS**

**Comment by TiraFire** [comment]
The issue has been resolved, the database is now hosted with azure and the connection is made in the code.  #155 This pull request is responsible for the config changes and #163 is responsible for making it work with windows due to an error with the USERNAME windows environment (explained in detail within the PR)
