### ISSUE TITLE
[Backend] - Unit Tests for Backend Functions (Routing, TypeORM, File Upload)

### ISSUE THREAD

**Issue by Mehrdadmaskull** [Data-Boom/SOEN490#117]
As a developer, I would like to have unit tests created for the past functions.

**Description:**
Units tests were not created for the past functions in the routing, TypeORM, and File Upload. This story will create the missing unit functions.

**Tasks Involved:**

- [x] Create unit tests for Routing
- [x] Create unit tests for TypeORM
- [x] Create unit tests for File Upload

**Acceptance Criteria**
- Certain percentage of coverage. (TBD?)

**Story Point** - 
**RIsk** - 
**Priority** -

**Comment by Mehrdadmaskull** [comment]
I'll be closing this story since we'll need to create other stories for the unfinished tasks.
Routing won't be part of our unit tests anymore (refer to the link below)
TypeORM will require more research
File Upload will require use of other frameworks, mocha, chai, etc.

[Unit Testing for Backend - Confluence](https://databoom.atlassian.net/wiki/spaces/DB/pages/74874906/Unit+Testing+for+backend)
