### ISSUE TITLE
[Backend] - File Upload Verifications and Error Handling [References: #71]

### ISSUE THREAD

**Issue by Mehrdadmaskull** [Data-Boom/SOEN490#118]
As a Developer, file uploads to the database must have verification and error handling.

**Description:**
The file upload feature from #71 requires a JSON file to add a new dataset into the database. This feature does not have the required verifications and error handling while creating the new dataset. This userstory needs to create a way to verify the JSON files format, the correct object layout, and the data types. If there are any errors, the errors must be handled.

**Tasks Involved:**

- [x] Verify file type
- [x] Verify JSON file outline
- [x] Verify Data Types
- [x] Error handling

**Acceptance Criteria**
- File type is verified (only accepts JSON)
- File outline is verified (Each required data is existent)
- Data types are verified (if data has database type requirements)
- Error handling for wrong file type, data type, and missing required data

**Story Point** -
**RIsk** - High
**Priority** - High

**Comment by GD-Dheer** [comment]
> Add request validations in backend and have a better error handling

This should also handle file upload cleanup, validations & add missing json attributes

**Comment by TiraFire** [comment]
Assigning @ratulkai93 to this story to replace GD for the time being, will modify other stories to give more tasks to everyone for this following week.
