### ISSUE TITLE
[Testing] - SonarQube follow-up Sprint 3

### ISSUE THREAD

**Issue by Mehrdadmaskull** [Data-Boom/SOEN490#119]
Address issues from SonarQube reporting (code smells, etc..)

**Tasks:**

- [x] Assess the SonarQube report, verify with each dev whether the bugs listed make sense
- [x] Document the valid bugs in the SonarQube report on Confluence
- [x] Document security vulnerabilities found in Sonarqube report on Confluence
- [x] Address each bug in separate branches backend/SonarqubeFixes and frontend/Codesmells
- [x] Address current code smells, technical debt, and security vulnerabilities

**Screenshot of [current report](https://databoom.atlassian.net/l/c/mouEVgYx):**
![image](https://user-images.githubusercontent.com/6520150/100400841-d0352880-3025-11eb-9bfe-3f8729872378.png)
                                                     **Fig 1. First hand view of the report**
![image](https://user-images.githubusercontent.com/6520150/100400851-d5927300-3025-11eb-8a17-c04c76f4e467.png)
                         **Fig 2. Section of the page showing a screenshot of the Sonarqube report results before addressing changes**
![image](https://user-images.githubusercontent.com/6520150/100400861-da572700-3025-11eb-8cb7-71a7647114b7.png)
                                                     **Fig 3. An example of documented bugs**

**Acceptance Criteria:**
- Confluence should have complete documentation 
 - Technical debt
 - Code smells
 - Security vulnerability
- All security vulnerabilities should be addressed & fixed
- Code smells should be decreased
- All bugs should be addressed and verified with devs

**Comment by JeremiahTee** [comment]
After reviewing the bugs and consulting the team, I decided that it is not necessary to create bugs for each of the bugs found by Sonarqube. This is because most of the "bugs" are code conventions. Each commit for each bug can be found on the report that I am developing on Confluence.

**Comment by TiraFire** [comment]
Approved and reviewed, acceptance criteria is met. Great job!

**Comment by JeremiahTee** [comment]
I wrote an page on Confluence on how to setup Sonarqube and in the same page, I documented all the bugs, security vulnerabilities, security hotspot and code smells. I fixed them as well with PRs #132 #133 which have now been merged into our develop branch.
Page can be found here:
https://databoom.atlassian.net/wiki/spaces/DB/pages/27131926/How+To+Setup+Sonarqube+Sprint+3+report+adressed
After these fixes, the results are the following:
![image](https://user-images.githubusercontent.com/6520150/100402959-89e2c800-302b-11eb-82d5-e531623baa59.png)
I am not sure why there is still 1 bug, 1 vulnerability, 1 security hotspot and 3 code smells as I have fixed them. I am guessing that there is a delay - these should all be 0. I will update this picture in the near future.
