### ISSUE TITLE
[Frontend] - UI tests concerning #77 Features using Selenium

### ISSUE THREAD

**Issue by Mehrdadmaskull** [Data-Boom/SOEN490#120]
As a Developer, I would like UI Tests to cover the frontend code (Client) portion of the database.

**Description:**
These specific UI tests are for the current code developed in the 3rd sprint and some 4th sprint features for the Graph Featureset #77 along with the other components. This includes the 
- Hiding datasets on the graph
- Deleting datasets on the graph
- Opening datasets on the graph
- Hiding data points on the graph
- Downloading datasets link/button in JSON
- Downloading PNG link/button
Selenium will be used to perform these UI tests.

**Tasks Involved:**

- [x]  Develop UI test for Hiding Datasets
- [x]  Develop UI test for Hiding Data points
- [x]  Develop UI test for Opening Dataset
- [x]  Develop UI test for Deleting Dataset
- [ ]  Develop UI test for download dataset link/button
- [ ]  Develop UI test for downloading PNG link/button

**Acceptance Criteria**
Acceptable UI tests for each of the following tasks mentioned above.
These tests should test the full range of the Graph page features of both the graph itself and the download buttons.

**Story Point** - TBD
**RIsk** - Low
**Priority** - High

**Comment by Mehrdadmaskull** [comment]
@TiraFire do we have user stories for these tasks:
 Develop UI test for download dataset link/button
 Develop UI test for downloading PNG link/button
