### ISSUE TITLE
[Frontend] - Unit Tests Concerning D3 and View Pages

### ISSUE THREAD

**Issue by Mehrdadmaskull** [Data-Boom/SOEN490#121]
As a Developer, I would like unit tests to cover the frontend code (Client) portion of the database.

**Description:**
Unit tests will be necessary to cover all lines of the code for an excellent code coverage. These specific unit tests are for the current code developed in the 3rd sprint.

**Tasks Involved:**

- [ ]  Research into what needs to be unit tested in the frontend
- [ ]  Develop Unit tests for the appropriate functions in the Graph View, and the File upload view.
- [ ]  Learn how to develop unit tests on D3 functions
- [ ]  Develop unit tests for the D3 functions if possible

**Acceptance Criteria**
Acceptable code coverage in the frontend (client) portion (Over 90% (too much?))

**Story Point** - TBD
**RIsk** - Low
**Priority** - High

**Comment by ds161833** [comment]
lets do research on what should be unit tested
