### ISSUE TITLE
Usability/Performance Tools Research and Selection

### ISSUE THREAD

**Issue by TiraFire** [Data-Boom/SOEN490#134]
As a Developer, I would like to do some research into usability and performance tools to be able to select the right one for our project.

**Description:**
To complete this story, there must be documented research into different usability and performance tools. This documentation must be found on the confluence project site "databoom.atlassian.net". Once the documentation is complete, the selection process begins and there must also be documentation on why one tool is chosen over the other based on our project needs.

**Tasks Involved:**

- [x]  Research and documentation of usability tools
- [x]  Research and documentation of performance tools
- [x]  Documentation of the selection process for usability tools
- [x]  Documentation of the selection process for performance tools

Acceptance Criteria
- Well documented research on both tools
- Well documented selection process of both tools

**Story Point** - 3
**RIsk** - Low
**Priority** - Med

**Comment by JeremiahTee** [comment]
The documentation is finally completed with this Confluence article titled "Deciding Performance Testing vs Usability Testing". In this article, I explore and discuss four different tools (two for performance, two for usability). I have also written the selection process used and justified why we have decided to go with **loadtest npm** library for performance testing. Here are some screenshots of the article - in case you have not access to Confluence.

![image](https://user-images.githubusercontent.com/6520150/100569518-5064c380-329c-11eb-986a-9d045f2f26c1.png)
![image](https://user-images.githubusercontent.com/6520150/100569530-5490e100-329c-11eb-8ba8-c05fbeae4eea.png)
![image](https://user-images.githubusercontent.com/6520150/100569538-59559500-329c-11eb-9419-830d6ef2fc4d.png)
![image](https://user-images.githubusercontent.com/6520150/100569543-5fe40c80-329c-11eb-929a-574c2c2f75df.png)
![image](https://user-images.githubusercontent.com/6520150/100569552-670b1a80-329c-11eb-8efe-fbaeb158d469.png)
![image](https://user-images.githubusercontent.com/6520150/100569562-6d999200-329c-11eb-8319-a52be1fc240a.png)
![image](https://user-images.githubusercontent.com/6520150/100569571-738f7300-329c-11eb-84ad-da63ccbfac4c.png)

This issue can now be closed.

**Comment by JeremiahTee** [comment]
I set the estimate to "3" as @TiraFire had forgotten to do so. The original estimate is found on the description of this issue when it was finalized 5-6 days ago.

**Comment by ds161833** [comment]
Amazing job!

**Comment by ds161833** [comment]
Criteria were met. The article is very easy to read. Closing the issue
