### ISSUE TITLE
[Frontend] - Visual Table of Saved Datasets/Graphs

### ISSUE THREAD

**Issue by TiraFire** [Data-Boom/SOEN490#139]
As a User, I would like to visually see the saved datasets/graphs in a table/list.

**Description:**
This is the frontend portion of the saved data #14 Task. It will include the table with a basic layout, a table with correct headers, and a list of the datasets and graphs along with unique details for each one.

**Tasks Involved:**

- [ ]  Create basic layout for table
- [ ]  Create table with headers
- [ ]  Display datasets/graphs in comprehensive fashion (Details to distinguish between them all)

The mockup can be found in the task #14 

**Acceptance Criteria**
- Table/List exists
- List of Datasets/Graphs
- Unique details for each (name of dataset, unique graph name, etc)

**Story Point** - 1
**RIsk** - Low
**Priority** - Medium
