### ISSUE TITLE
[Frontend] - Visual Table of Uploaded Datasets

### ISSUE THREAD

**Issue by TiraFire** [Data-Boom/SOEN490#142]
As a User, I would like to visually see the upload datasets in a table/list.

**Description:**
This is the frontend portion of the Uploaded Datasets View #15 Task. It will include the table with a basic layout, a table with correct headers, and a list of the datasets along with unique details for each one.

**Tasks Involved:**

- [x]  Create basic layout for table
- [x]  Create table with headers
- [x]  Display datasets in comprehensive fashion (Details to distinguish between them all)

The mockup can be found in the task #15  

**Acceptance Criteria**
- Table/List exists
- List of Datasets/Graphs
- Unique details for each (name of dataset, unique graph name, etc)

**Story Point** - 1
**RIsk** - Low
**Priority** - Medium
