### ISSUE TITLE
[Frontend] - Visual Display of User Details and Settings

### ISSUE THREAD

**Issue by TiraFire** [Data-Boom/SOEN490#144]
As a User, I would like to visually see my user details as well as the option to change them.

**Description:**
This is the frontend portion of the User Details and Settings #16 Task. It will include a basic layout including all the parameters Name (first and last), D.O.B, Email, and Organization, and a button to change and save them.

**Tasks Involved:**

- [x]  Create basic layout for the Name (first and last), D.O.B, Email, and Organization
- [x]  Create buttons to change each individual setting (extra for password)
- [x]  Pop-up to change settings

The mockup can be found in the task #16

**Acceptance Criteria**
- Display for Name (first and last), D.O.B, Email, and Organization
- Buttons to change each detail mentioned above
- Button to change password
- Correct pop-up to change

**Story Point** - 1
**RIsk** - Medium
**Priority** - Medium
