### ISSUE TITLE
[DB] - Populate Database with Datasets from Jamiel's Github

### ISSUE THREAD

**Issue by TiraFire** [Data-Boom/SOEN490#148]
As a developer, I would like a populated database containing the datasets from the caltech website.

**Description:** 
Jamiels Github already scraped the caltech website and has all the datasets within. This story must go into the github, understand the code, connect to the database, export all the datasets and their metadata, format the datasets to fit our database, and import these datasets into our database in azure.

**Tasks Involved:**

- [x]  Connect to Jamiels database (ZIP file found in the google drive)
- [x]  Export all the datasets and metadata
- [x]  Import into our Azure database
- [x]  Format datasets to fit our database
- [x] Document the work on Confluence

**Acceptance Criteria**
- Populated database
- ALL the datasets from the caltech site

**Story Point** - TBD
**Risk** - High
**Priority** - High

**Comment by JeremiahTee** [comment]
To leave some information on the progress of this issue,
On December 22nd I had a meeting with Jessica @TiraFire and we went over the dataset-builder.py script together. This script scrapes the Caltech website and builds a JSON called datasets.json. This JSON contains all the 387 datasets in a specific formatted order that would help us in populating the database in the easiest way possible.

The week following December 22nd, Jessica worked on the dataset-points.py script that scraped all the .txt files including dataset points and built a JSON in a formatted way, with the same purpose of having a specific format to parse through and populate the database in the easiest way.
She also wrote another script that would organize all the authors in a file called "authors.json". 

On December 28th, I wrote the report explaining this work on Confluence, the title of the article: ["[Report] Scrapers to build datasets.json"](https://databoom.atlassian.net/wiki/spaces/DB/pages/122814761/Report+Scrapers+to+build+datasets.json)

Screenshots of the breakdown of datasets-builder.py: 
![image](https://user-images.githubusercontent.com/6520150/103472032-1fbdf100-4d56-11eb-83a6-fcd5ba61dee5.png)
Figure 1: part of the datasets-builder.py script

![image](https://user-images.githubusercontent.com/6520150/103472035-35331b00-4d56-11eb-8928-36dc7d8766a2.png)

Figure 2: part of the small breakdown section of the datasets-builder.py script

**Comment by JeremiahTee** [comment]
We did not commit the builder scripts and .txt files at the time as we were collaborating back and forth, and we actually met on different days throughout the past weeks. These scripts were only finalized recently. However, today on January 2nd we met over Discord and as we already completed the "scraping" part - we started building the queries.

The process for building the queries to execute on MySQL workbench is as following:
- Loop through the JSON files built with the three different python scripts: dataset-builder, datapoints-builder, authors-builder. 
- For each object in each JSON file, write the SQL query with the needed data. Since JSON objects can be used in Python and its "sub-objects" can be accessed, this was fairly easy to do in Python.

So far, we were able to write four different scripts (commit 66947f3) called:
- authors-script.py
- publications-script.py
- publications-authors-authors-script.py
- composition-script.py


Each script "builds" the queries for each corresponding table (referred to in the name of the script). Each of these queries are written (stored) in a corresponding .txt file.
For example, **authors-script.py** will produce **authors-query.txt**.
The composition-script.py contains the code for the materials and dataset-materials-material table as well.

**Comment by JeremiahTee** [comment]
As aforementioned, so far @TiraFire and I worked on the following scripts:
- authors-script.py
- publications-script.py
- publications-authors-authors-script.py
- composition-script.py
- found in commit  66947f3

These scripts produced the txt files containing the specific queries to populate the corresponding tables. 
Txt file queries found in 23edfeb and 47fef30

These queries only insert into the databoom-db-test database as we want Sean @Arrow105 and possibly our stakeholder to approve these changes before we insert to the real database. 

What is left to do, is to write the scripts that will build the queries to populate the following tables:
- Category 
- Subcategory 
- Dataset 
- Units 
- Representations 
- Datapoints 
- Datapointcomments

As discussed with Sean and Jessica, we must populate the rest of the tables in this following order because of the foreign keys (relations) between each of those tables observed in our ER diagram. 
I will write a Confluence articles documenting this in detail soon.

**Comment by JeremiahTee** [comment]
As mentioned in the PR #190 , a detailed report has been written on Confluence. It can be accessed here:

This article describes all the work from this PR in detail.
[**[Report] How To Populate Database using scraped JSONs**](https://databoom.atlassian.net/wiki/spaces/DB/pages/170557454/Report+How+To+Populate+Database+using+scraped+JSONs)

An article explaining the builder scripts has also been written:
[**[Report] Scrapers to build datasets.json and datasets-with-datapoints.json**](https://databoom.atlassian.net/wiki/spaces/DB/pages/122814761/Report+Scrapers+to+build+datasets.json+and+datasets-with-datapoints.json)

PR #190 is now awaiting reviewal/approval before this issue can now be finally closed 👍
