### ISSUE TITLE
[DB] Evaluate Caltech Python Scraper from Jamiel Rahi

### ISSUE THREAD

**Issue by JeremiahTee** [Data-Boom/SOEN490#152]
As a developer, I would like to know whether a pre-existing Python scraper of the Caltech Detonation website can be re-used and modified in order to scrape the website in the fashion that I want so that I can proceed to populate another DB. 
**Note** This scraper was developed by JamieI Rahi and can be found [here](https://github.com/closetothe/detdb/tree/dev/scraper)

**Description:** 
Jamiel's Github already scraped the Caltech detonation website and has all the datasets within in a raw format. The issue is that the way that the datasets were scraped, formatted and inserted in his own database is not documented. What his repo contains is the formed database and the scrapers (python scripts) that were used to do the scrapings. We must figure out whether these scrapers can be re-used and modified to our purpose: to scrape the Caltech website in the way we want to and populate our remote DB in the most efficient way.

**Tasks Involved:**

- [x]  Investigate Jamiel Rahi's scrapers and evaluate whether they can be used and re-purposed for scraping data the way we want to scrape it: with the SQL relations that fit our current remote DB.
- [x] Run the scrapers if possible and confirm that they do work (possibly using MySQL workbench for verifying the DB)
- [x] Document any findings on Confluence

**Acceptance Criteria**
- Documentation of findings on Confluence in a form of small report
- This documentation must state whether the scrapers are functionals and whether they can be modified to scrape the data from the Caltech website and gather that raw data in the structure (SQL relations) that we want. 

**Story Point** - TBD
**Risk** - Med
**Priority** - Med

**Comment by JeremiahTee** [comment]
During an initial 1 hour and a half programming pair session with @TiraFire, we reviewed most of the content of Jamie's repos. Jessica also took the liberty to explain to me the sample .json that has and is currently being used for populating our local database. She went over the three distinct cases of datasets that might or might not have ranges as values. This discussion and explanation was documented in a .txt file and images - soon to be uploaded to Confluence.

My task is to currently write the Confluence article, have it proof-read by @TiraFire . I will also have a secondary meeting where we will attempt to run the scrapers or at least identify where the data points are stored. So far we were able to identify, and verify the dataset table in Jamie's database. Our findings were correct - there are 387 distinct datasets listed in the website - and there are 387 scraped datasets by Jamie.

**Comment by JeremiahTee** [comment]
An article on Confluence titled ["JsonSample.json dataset sample explained" ](https://databoom.atlassian.net/wiki/spaces/DB/pages/80936971/JsonSample.json+dataset+sample+explained)has been written on December 7. It covers an explanation of the .json used to populate our current local database - the same .json provided by our stakeholder Kiyanda. 

I need @TiraFire to proof-read this article, offer suggestions & feedback on what to improve.

I am also currently working on an initial report of our findings, with detailed explanations and figures.

**Comment by JeremiahTee** [comment]
After a 2 hour meeting with Jessica, we have listed and found all the data that was scraped and that needs to be inserted in our DB. I documented all of the findings in a Confluence article titled[ "[Report] Scraped data from "detdb" explained US #152"](https://databoom.atlassian.net/l/c/pLg4v1qf)

I did not run the scrapers as the scraped data was available to us readily. This issue can now be closed upon review @TiraFire @Arrow105

**Comment by JeremiahTee** [comment]
Some screenshots of the article
**Introduction of the article** (Fig 1.)
![image](https://user-images.githubusercontent.com/6520150/102645806-094a4f80-4131-11eb-9442-7b931e170eef.png)
                                                                                       Figure 1

**Dataset breakdown section** (Fig 2.)
![image](https://user-images.githubusercontent.com/6520150/102645819-0f403080-4131-11eb-88c5-c84a0b319844.png)
                                                                                       Figure 2

**What we need and we have found section** (Fig 3.)
![image](https://user-images.githubusercontent.com/6520150/102645846-18c99880-4131-11eb-9e8a-c135aee27e60.png)
                                                                                       Figure 3

**First part of the table breakdown: Table in ERD, Data needed & its type, and data location** (Fig 4.)
Table in ERD refers to the name of the table in the ER diagram. Data needed is the data that we need in order to populate our DB - this is either already scraped or has to be scraped. If it is scraped, it is noted in the _data location_ column. 
                                                                                    


![image](https://user-images.githubusercontent.com/6520150/102645865-22530080-4131-11eb-905f-5b2fcc6fc8cc.png)
                                                                                          Figure 4

**Second part of the table breakdown.** (Fig. 5)
![image](https://user-images.githubusercontent.com/6520150/102645880-28e17800-4131-11eb-8abe-773a904992bb.png)
                                                                                          Figure 5

**Comment by JeremiahTee** [comment]
In a small meeting, I reviewed my article with Sean and Jessica. Sean left comments on the appropriate places where it needed more explanation or clarification. I addressed those comments on the spot (Fig 6.)

![image](https://user-images.githubusercontent.com/6520150/102730942-5df1f400-4304-11eb-8cf4-26a4ebc42549.png)
Figure 6

**Comment by TiraFire** [comment]
This story is completed to best of our abilities in regard to the research of the "already scraped" github by another student (with given permission). The hopes that the scraping would be done in a way for us to use easily was sadly not as much as hoped. It seems that the old student decided to test certain things out while doing the scraping and the database creation so it would prove more difficult to re-engineer it than to scrape some ourselves. Therefore, with this story closed, the scraping can commence and the database can be uploaded with the datasets. Thank you @JeremiahTee for this excellent confluence page describing our findings. Great job!
