### ISSUE TITLE
Research Paper Analysis

### ISSUE THREAD

**Issue by JeremiahTee** [Data-Boom/SOEN490#19]
As a User, I would like to be able to upload research papers and have them analyzed.

**Description**: 
This is the portion where the user is able to upload research papers and have them analyzed. This means the paper will have all the dataset details extracted.

Due to the connection with ML and CV, this is only the stories for frontend and UI testing.

**Tasks Involved:**

- [x] Create an easy to follow visual component
   - [x] Upload Research Paper
   - [x] Preview of Dataset details extracted
- [x] UI Test #40  

Mockup To Come.

**Acceptance Criteria**
- Option to upload research paper (PDF)
- Preview is correct

**Story Point** - 2
**Risk** - Low
**Priority** - Medium
