### ISSUE TITLE
Link User Page Frontend and Backend to Each Other

### ISSUE THREAD

**Issue by silent-po2** [Data-Boom/SOEN490#195]
**Description**: The various user pages will be able store and fetch information from the database instead of working with filler data as they are currently. 

This task involves connecting the user page to the database. This means at the end of the story, the user page must show the correct user details, the user's saved datasets and graphs, as well as a list of all their uploaded datasets. This also includes making sure the links to the corresponding datasets/graphs work and that the editing of information is saved and loads the newest information.
 
**Tasks Involved:**

- [x] Connect Frontend to Backend for User Details
- [x] Connect Frontend to Backend for Saved Datasets/Graph
- [x] Connect Frontend to Backend for Uploaded Datasets

Story Point - 2
Risk - Low
Priority - Medium
