### ISSUE TITLE
Save A Dataset/Graph Feature

### ISSUE THREAD

**Issue by TiraFire** [Data-Boom/SOEN490#197]
As a User, I would like to save a graph and/or dataset to be able to quickly access them from the user page.

**Description:** This story involves three parts. The first part is the UI which the mockup below will display. Next to each graph (with different datasets), there will be a empty star icon if the graph is unsaved, and a full icon if it is. They have an option to save as many graphs as they want as long as the graphs differ by at least 1 dataset. To save a dataset, there will be the same icon on the dataset line (refer to the mockup). Let the user save the dataset/graph with a specific name/comment. The endpoints should save the details of the graph/dataset. These details will involve talking to Kiyanda to gather what he would like saved for the graph. Otherwise, the unique ids, or list of, for the datasets are required as well as a name/comment.

**Tasks Involved:**

- [x]  Gather requirements from Kiyanda on Graph saving (which elements he would like to save)
- [x]  Create the frontend elements (the star icons for the graphs and the datasets)
   - Make sure the UI is obvious, and include "help" bubbles or other to make sure they know how what the icons do and how to use them
- [x]  Create the endpoints to save this information into the backend
- [x] Connect the frontend and backend to have it fully functional

Mockup Image:
![image](https://user-images.githubusercontent.com/25015601/104249830-34774480-543a-11eb-929d-607c94139e7a.png)

**Acceptance Criteria**
- The UI is functional and obvious to use
- The endpoints work to save the details in the backend
- The connection between the frontend and backend must work (saving a graph should save and show in the users page)

**Story Point** -  
**RIsk** - 
**Priority** -
