### ISSUE TITLE
[Testing] - SonarQube Code Smells, Security Fix Sprint 6

### ISSUE THREAD

**Issue by TiraFire** [Data-Boom/SOEN490#223]
As a Developer, I would like to have SonarQube run and have the security hotspots, bugs and technical bugs that accumulated over Sprint 5 addressed, fixed and documented.

**Description:**
During development, there is a lot of code added, these codes can bring bugs and code smells. To have our code from becoming poor, running sonarqube at various times, we can keep up to date with these bugs and code smells. This issue is one of those moments. Run the tests, study the issues/code smells, and fix them.

**Note** Sonarqube code smells and security hotspots haven't been addressed in sprint 5, and so it's time to address them in this Sprint 6.

**Tasks Involved:**

- [x]  Run the Sonar Scanner & examine report on Sonarqube
- [x]  Address & fix the technical debt (code smells), security hotspots and bugs
- [x]  Document the security hotspots and major fixes on Confluence

**Acceptance Criteria**
- All the technical debt, security hotspots and bugs flagged by Sonarqube are addressed and fixed
- Security hotspots and major bugs are documented on Confluence
