### ISSUE TITLE
Signout

### ISSUE THREAD

**Issue by ds161833** [Data-Boom/SOEN490#234]
As a user, I would like to be able to sign out of my account with a sign out button.

**Description:**
The sign in works, but a sign out button does not exist. The user is not able to sign out of their account once they sign in. This story needs to create a button to sign out once a user signs in. This button should remove the user from the local browser storage.

**Tasks Involved:**

- [x]  Create a sign out button only seen if the user is logged in.
- [x]  Remove the user from the local browser storage when it is clicked.
- [x]  Redirect the user to the sign in page.

Mockup Image or link to Mockup:
![image](https://user-images.githubusercontent.com/25015601/105609550-1681dc00-5d78-11eb-8918-d15e0244b900.png)

**Acceptance Criteria**
The user clicks sign out, the user is removed from local browser storage
