### ISSUE TITLE
[Frontend] - Create User Submitted Datasets Reviewal Page

### ISSUE THREAD

**Issue by GD-Dheer** [Data-Boom/SOEN490#276]
As a User, I would like to see the progress on my uploaded datasets under review. 

This page would show all the unapproved datasets. If a dataset is flagged, it should show the flagged comment as well as the option to either approve or edit the dataset. If the dataset is edited, it will fall under review again. If they decide to approve, it will be removed from reviewal and the flag will be deleted.

**Tasks :**
- [ ] Create the UI for this based based on the mockup
- [ ] Connect the approval to the approved API
- [ ] Allow the user to edit the dataset if flagged
- [ ] Connect the edit and save option to the review API (To put it under review again)
- [ ] Call the queries to list the users unapproved datasets

**Acceptance Criteria**
A user can choose between approve or edit if flagged
A user can see a list of their unapproved datasets
The dataset is put under review again if edited
The dataset is approved if selected to approve after a flag

**Comment by ds161833** [comment]
closing as a duplicate of a closed story
