### ISSUE TITLE
[Computer Vision] - Cell Size Analyzer to measure cell sizes and isolate edges

### ISSUE THREAD

**Issue by GD-Dheer** [Data-Boom/SOEN490#279]
As a User, I would like to upload a .PNG image of a detonation cell, and have it automatically analyzed by computer vision so that it calculates the cell sizes and returns the appropriate measures. 

This issue is an Epic that can be broken down into the following user stories / tasks:

Computer vision
- [x] Task 1: Isolate the edges of the cells in the image -> 8 pts 
- [x] Task 2: Measure between the edges (cell size) -> 13 pts
- [x] Task 3: Display corresponding cell size IDs in the cells -> 5 pts

Front-end
- [x] Task 1: Verify that a .png is given -> 1 pt
- [x] Task 2: Connect script to service & service to front-end -> 3 pts
- [x] Task 3: Display image with cell size IDs in the cells on the page -> 1 pt
- [x] Task 4: Display average value of cell size -> 1 pt
- [x] Task 5: Display arrays of cell sizes with their corresponding cell size IDs -> 1 pt

Acceptance Criteria
- User must be able to upload a .png file of detonation cell image and have it validated
- Cell sizes for any given detonation cell image must be calculated using computer vision
- An array of cell sizes with their corresponding cell size IDs must be displayed on the page
- An average value of cell sizes is displayed on the page (confirm with Stakeholder)
- An image with the cell size IDs in each cell should be displayed and/or able to be downloaded

Risk - Med
Priority - High
