### ISSUE TITLE
[Frontend] & [Backend] - Update user details to include ORCID ID and remove DOB

### ISSUE THREAD

**Issue by GD-Dheer** [Data-Boom/SOEN490#282]
As per stakeholder request, he wants website to store a 16 digit ORCID ID instead of Date of Birth

**Description** 
This story will update frontend, backend and database to include ORCID ID instead of Date Of Birth. 

**Tasks**
- [x] Task 1: Update database Accounts column DOB to ORCID ID (int) 
- [x] Task 2: Update SignUp form on Frontend to accept ORCID instead of Date of Birth
- [x] Task 3: Update SignUp API on Backend to accept ORCID instead of Date of Birth
- [x] Task 4: Update fetchUserDetails to return ORCID instead of Date of Birth

**Acceptance Criteria**
- User should be able to store ORCID
- User should be able to see their ORCID when visiting their Profile Details page
