### ISSUE TITLE
[Frontend] - Implement features previously implemented on D3 lib

### ISSUE THREAD

**Issue by GD-Dheer** [Data-Boom/SOEN490#283]
As a user, I would like to see all features previously implemented in the new graphing library

**Description** 
While migrating to amcharts for new stakeholder requirements, many of the previously implemented features were no longer working.

**Tasks**
- [ ] Axes Control switch between Linear and Log (independent axes)
- [ ] Ability to increase boundaries
- [ ] Check if there is an ability to drag/move the graph

**Acceptance Criteria**
Give the option to switch between Log and Lin scales
Add the option to choose the boundaries (increase or decrease)
Be able to drag/move the graph around
