### ISSUE TITLE
[Backend] - Implement sign out API

### ISSUE THREAD

**Issue by GD-Dheer** [Data-Boom/SOEN490#284]
As a developer, I would like to destroy the existing cookie session when an user signs out from the website.

**Description** 
Currently, the sign out functionality does not remove the cookie session and this causes the website to continue acting like the user is logged in. This even causes the bug #264 so this story must fix this.
To complete this issue, you need to create an endpoint that clears cookie header of the incoming request. 

Stack Link: https://stackoverflow.com/questions/27978868/destroy-cookie-nodejs

**Tasks**
- [x] Task 1: Endpoint Creation
- [x] Task 2: Remove cookie header safely
- [x] Task 3: Create call from frontend to this API

**Acceptance Criteria**
API calls to the backend should not contain a filled cookies header.
Fixes #264
