### ISSUE TITLE
Allow Superuser (Kiyanda) to add/remove Admins

### ISSUE THREAD

**Issue by TiraFire** [Data-Boom/SOEN490#294]
As a superuser I want to be able to add new admins by email, and remove admin permissions from them.

**Description** 
This epic encompasses all requirement needed for an existing superuser to add and remove admins on the platform. This lets Kiyanda grant admin permissions by inputting a user email. 

The user must already exist in the system with a valid email to become an admin.

**Tasks**
- [x] Task 1: Create mockup for UI design
- [x] Task 2: Develop UI page admin creation
- [x] Task 3: Develop backend API to support this feature
- [x] Task 4: Add a system test for this feature

**Acceptance Criteria**
- Ability to create new admins
