### ISSUE TITLE
Categories and subcategories

### ISSUE THREAD

**Issue by TiraFire** [Data-Boom/SOEN490#296]
**Description** 
This epic encompasses all the work required to handle categories and subcategories in the platform. There are changes to be done on the datasets page when retrieving and displaying the correct category and appropriate subcategory and super user functions for adding/modifying categories/subcategories.

**Tasks**
- [x] Task 1: Update backend call when calling /fetchCategories to return categories with associated subcategories
- [x] Task 2: Create backend API to add/modify categories and subcategories as a super user
- [x] Task 3: Create Mockup to visualize FE page for super user
- [x] Task 4: Create FE page form mockup to support category/subcategory updates
- [x] Task 5: Add system test for this epic

**Acceptance Criteria**
- Categories & Subcategories must be modifiable
