### ISSUE TITLE
Scrape citation information from DOI entry

### ISSUE THREAD

**Issue by TiraFire** [Data-Boom/SOEN490#297]
As a user, I would like to have an option to "Search by DOI" for an option to enter a reference when adding a dataset.

**Description** 
There should be an option on the manual upload form that gives the user a chance to insert a DOI and scrape DOI.org. It will scrape DOI.org for the reference information and then map it to the dataset manual upload form.

**Tasks :**
- [ ] Write a script to scrape the doi.org with a given DOI
- [ ] Put in the frontend UI and connect it to the service
- [ ] Map the given information to the form

**Mockup :**
To come.

**Acceptance Criteria :**
Verify the DOI given is valid (https://www.crossref.org/blog/dois-and-matching-regular-expressions/)
Reference is mapped to the values
Error messages appear
