### ISSUE TITLE
[Frontend] - Found datasets on the Search results, should contain links to the dataset page

### ISSUE THREAD

**Issue by TiraFire** [Data-Boom/SOEN490#303]
As a User, I would like to review full contents of a dataset from the results of a search.

**Description:**
This page will display the specific dataset along with its details. 

An example can be taken from the GraphView page that when provided graphStateId loads it from BE and displays the saved graph. And the links are accessible through the Profile page -> saved graphs

**Tasks Involved:**
- [x] Change the search page results list to call the API
- [x] Create the layout for the single dataset page
- [x] Fill out the form with the corresponding dataset values
- [x] Make sure the layout has a "Back to search page" button that is functional

Mockup:
Create a mockup

**Acceptance Criteria**
- Search Results's datasets' name should be a link that leads to the dataset page with dataset id e.g. website.com/dataset/datasetId
- Dataset is displayed if accessed by /dataset/{datsetId} link and the form is not editable
- Go back to search page through "back" button

**RIsk** - Low
**Priority** - Medium

**Comment by ds161833** [comment]
What needs to happen is that the DatasetView page, if id parameter was given, needs to request the dataset from backend and display it with editable=false.
e.g. if DatasetUploadView (needs to be renamed into DatasetView) is accessed with website.com/dataset, the page is empty (i.e. the user is creating a new dataset). If accessed with website.com/dataset/123 means FE needs to request dataset with id 123 from backend and display it. In that case the dataset is not editable.
