### ISSUE TITLE
[Operations] - Set up the environment on Stakeholders Server

### ISSUE THREAD

**Issue by TiraFire** [Data-Boom/SOEN490#304]
As per stakeholder, the environment needs to be setup on his Concordia Hosted Linux Machine

**Description** 
Setup NODEJS backend on his server, then setup React Frontend. From previous email exchanges, the school will support PHP and mysql database. We will be required to email their IT department to know the correct procedure for deploying on their servers such as what directory to install in (likely to serve from var/www/html), obtaining a domain name, adding NGINX seems to be good practice for a NODEJS application

Depending on what IT support answers, we could alternatively deploy using docker providing all configs ourselves

Update: 
- Will not use Docker
- Kiyanda system is bare so we can install everything ourselves
- We already have a hostname available: databoom.encs..... 
- Once FE is running on port 80, we can run the BE on a different port internally

**Tasks**
- [x] Task 1: Install nodejs and verify open ports (22 & 80 & 443)
- [x] Task 2: Setup new user permissions (should not work under root)
- [x] Task 3: Clone project into appropriate directory & npm install (production dependencies ONLY)
- [x] Task 4: Setup NGINX as reverse proxy (if allowed)
- [ ] Task 5: Application needs to be configured to run as a background service (install something like pm2 to manage)

**Acceptance Criteria**
- Full application should be assessable from accessing concordia domain name
