### ISSUE TITLE
Add Support to parse TXT and CSV containing Datapoints 

### ISSUE THREAD

**Issue by TiraFire** [Data-Boom/SOEN490#305]
As a User, I would like to upload CSV & TXT files with datapoints that _optionally_ have variables as column headers and datapoints as rows.

Frontend is required to map these datapoints into the template upload form.
Backend is required to parse the data and return data in the response

Tasks Involved:

- [x] Task 1: Allow file upload to accept CSV, TXT files in the frontend
- [x] Task 2: Add backend API to support CSV parsing
- [x] Task 3: Add backend API to support TXT parsing
- [x] Task 4: Map return data to manual upload form. 

Acceptance Criteria
- User must be able to upload CSV & TXT file
- User should see datapoints uploaded into the manual dataset form.
- System tests must be added

Risk - Low
Priority - Med
