### ISSUE TITLE
[Frontend] - Allow admins to manage categories/subcategories

### ISSUE THREAD

**Issue by GD-Dheer** [Data-Boom/SOEN490#341]
As a admin, I would like to add, remove, edit categories and corresponding sub-categories.

**Description** 
Categories and subcategories should not be able to be modified by regular users but to be able to adapt to changes, there should be a way for admins to be allowed to add new categories and their corresponding subcategories. Not only this, but to be able to remove ones, and edit them.

**MOCKUP:** https://www.figma.com/file/MmvzMxb3sK8taRBxRalorD/Dataset-Review?node-id=100%3A705

**Tasks**
- [ ] Create the frontend to follow said mockup
- [ ] Connect the frontend to call the APIs to add/remove or edit
- [ ] Create snackbars for the error messages and success messages
- [ ] Validate if the category or subcategories already exist
- [ ] Connect the frontend to fetch all the categories/subcategories

**Acceptance Criteria**
Admins are able to edit, remove, add categories/subcategories
All subcategories have a corresponding category

**Comment by GD-Dheer** [comment]
Story pushed to sprint 9
