### ISSUE TITLE
Unit Conversion

### ISSUE THREAD

**Issue by GD-Dheer** [Data-Boom/SOEN490#347]
As a User, I would like to have the website support numerous dimensions and their respective units units for the dataset variables. 
**Vocab:** 
dimension - physical quantity like speed, mass, length, acceleration, force, etc.
unit - unit of the dimension e.g. meters, mm, km for length; kg, lbs, tonne for mass
variable - a part of dataPoints of a dataset, dataset can have many variables each represented by name, dimension, unit, e.g.:
name: Cell Width, dimension: length, unit: mm

**Description** 
During a dataset upload, each variable is defined by name, dimension and unit. Not all the datasets will conform to the same units so there needs to be a way to support numerous units to store and to convert to the same units when viewing in a graph. There is also the issue of being able to add/delete/edit units which is a power that the admins of the website will need.

- Allow the admin to add/remove/edit units and add their conversion equation.
- Users should be able to select the dimensions and units for their variables
- When viewing the graph and specifying variables for the axes (e.g. Cell Width against Initial Pressure), users should be able to select any units they want (e.g. m), and all datasets, that may have a dimension (e.g. length) represented by different units (e.g. mm or km)
- Allow downloading datasets in different units - **low priority**, an enhancement

Create queries to obtain the dimensions and the unique units from the database
Create queries to add/remove/edit units

**Tasks**
- [x] Create the frontend for the add/remove/edit units and conversion equations
- [x] Connect the frontend to call the APIs to add/remove/edit units and conversion equations
- [x] Change the way the user add units in the dataset upload form
- [x] Connect the conversion API for the graphs
- [x] Create option to download in different units
- [x] Call the API to convert the units when downloading

**Acceptance Criteria**
Admins can add/remove/edit units and their conversions to the base unit
Users can add a variable using the units from the database
Users can convert to different units inside the graph page
Users can download datasets in different units
