### ISSUE TITLE
[Backend] - Develop API to support creation of new admin accounts

### ISSUE THREAD

**Issue by GD-Dheer** [Data-Boom/SOEN490#348]
As owner, I would like to modify the status of an existing user to have admin privileges. 

**Description** 
An incoming request on this API would modify the existing status of a user and switch on the admin flag of their account. 
This story now includes the creation of a super user. This path must be superuser protected.

Table Changes:
Update Accounts table from isApproved to permissionLevel (user, admin, root)

Accepting params: User email

**Tasks**
- [x] Task 1: Develop GET api route fetch all admins 
- [x] Task 2: Develop PUT api route to change user status (update user to admin, remove admin permissions)
- [x] Task 3: Endpoint must be protected to only allow access to superuser
- [x] Task 4: API call /fetchUserDetails must be updated to also return privilege level

**Acceptance Criteria**
- A newly modified user account is able to access an admin API that was not previously accessible
- Permissions page shows all system admins

**Comment by ds161833** [comment]
@GD-Dheer @Arrow105 I think we also need a 'get admins' API to display current admins in the system, so that admins can go and see who is an admin, what about remove admin? what if the person decided they dont want to admin anymore?

**Comment by GD-Dheer** [comment]
> @GD-Dheer @Arrow105 I think we also need a 'get admins' API to display current admins in the system, so that admins can go and see who is an admin, what about remove admin? what if the person decided they dont want to admin anymore?

@ds161833 Good catch. Will update the ticket

**Comment by GD-Dheer** [comment]
> > @GD-Dheer @Arrow105 I think we also need a 'get admins' API to display current admins in the system, so that admins can go and see who is an admin, what about remove admin? what if the person decided they dont want to admin anymore?
> 
> @ds161833 Good catch. Will update the ticket

Ticket was updated again after getting new requirements from stakeholder
