### ISSUE TITLE
[Frontend] - Create UI for approving new Admins

### ISSUE THREAD

**Issue by GD-Dheer** [Data-Boom/SOEN490#350]
As an Admin, I want to be able to add and remove admins as well as see the list of current admins, their first name + last name + email.

**Description** 
The page needs to exist to be able to add a new admin while giving the option to remove old ones. This will follow the mockup in #349.

**Tasks**
- [x] Create the UI based on the mockups #349 
- [x] Connect frontend to call the queries to load the list of admin
- [x] Connect the API to remove admins
- [x] Connect the API to add new admins

**Acceptance Criteria**
- only superuser can access the page
- New admins are able to be created from the UI
- Old admins can be removed
- List of current admins is visible
- Success and fail on add and remove must be displayed messages work
**UPDATE** 
follow this wireframe's structure for the page, it is okay if there are slight differences between the implemented page and the mockup, lets try to follow all the patterns we followed before https://www.figma.com/file/4dELUUuDxeQeSeQMMhVOjP/Getting-somewhere?node-id=0%3A1
