### ISSUE TITLE
[Backend] - API creation & Updates to support Category Changes

### ISSUE THREAD

**Issue by GD-Dheer** [Data-Boom/SOEN490#358]
**Description** 
Superuser should be able to add/modify categories and subcategories in the system. Updates must also be made to existing APIs to properly link a subcategory with its parent category

This includes
**Tasks**
- [x] Task 1: Update subcategories table with Category reference so each subcategory is part of a category
- [x] Task 2: Update IDatasetModel to now return a categoryID instead of category name
- [x] Task 3: Update /category to return ICategory Model
- [x] Task 4: Create POST /api/v1/Category API to add a new category & respective sub-category into the system
- [x] Task 5: Create PUT /api/v1/Category API to update a 
- [x] Task 6: Delete /api/v1/Category API to delete a category and ALL respective subcategories

interface ICategory {
name: string
id: number
subCategories: subCategories[]
}
interface ISubCategory {
name: string
id: number
}

**Acceptance Criteria**
- ICategory Model must be returned on a call to /fetchAllCategories
- Superuser must be able to add a category and subcategory
- Superuser must be able to modify a category and subcategory
