### ISSUE TITLE
[Backend] - Adapt Dataset API to new unit model

### ISSUE THREAD

**Issue by ds161833** [Data-Boom/SOEN490#366]
**Description** 
We recently have updated the way a variable is represented, it used to be `name, repr, units` but now it is represented as `name, unitId, dimensionId`. **ALL** our api that creates a new dataset, updates existing dataset, or returns dataset(s) needs to be able to return variables represented in the new fashion.

**implementation details**

**Tasks**
- [x] update the search datasets API to return
- [x] update data upload API
- [x] change the model returned on search datasets completely from IRemoteDatasetModel to IDatasetModel (these two can be found in Client/src/Models/Dataset)

**Acceptance Criteria**
 - when I create/update a dataset where my variables are represented with unitId and dimensionId, the API accepts this model. DimensionId is one of the existing in the system dimensions, and UnitId is one of the units of the of a dimensionId
 - when I use the api to search for datasets I get back datasets with variable that contains `name, dimensionId, unitId`
