### ISSUE TITLE
[Operations] - Database Migration

### ISSUE THREAD

**Issue by GD-Dheer** [Data-Boom/SOEN490#372]
**Description** 
MYSQL database migration to concordia servers. We know concordia already supports mysql db. 

**Tasks**
- [x] Task 1: Complete a backup of our mysql 'production ready' DB (dump it)
- [x] Task 2: SCP to concordia servers into where they have mysql installed (if mysql is not installed, then it can be installed)
- [x] Task 3: Restore backup into mysql

**Acceptance Criteria**
- Should be able to connect to migrated DB with mysql client

**Comment by silent-po2** [comment]
As of now, MySQL ver 5.7.33 is installed on the server and the database dump has been imported.
