### ISSUE TITLE
[Operations] - Run Security Scan before & after deployment

### ISSUE THREAD

**Issue by GD-Dheer** [Data-Boom/SOEN490#373]
**Description** 
This task involves completing a security scan prior and post deployment. This is to make sure the codebase is not vulnerable to any Common Vulnerabilities & Exposures

**Tasks**
- [ ] Task 1: Run SonarQube before and after deployment
- [ ] Task 2: Run OWASP ZAP before and after deployment
- [ ] Task 3: Run WAPITI before and after deployment
- [ ] Task 4: Run sqlmap before and after deployment
- [ ] Task 5: Run npm audit before and after deployment

**Acceptance Criteria**
- All code related configurations & vulnerabilties will patched

**Comment by GD-Dheer** [comment]
> **Description**
> This task involves completing a security scan prior and post deployment. This is to make sure the codebase is not vulnerable to any Common Vulnerabilities & Exposures
> 
> **Tasks**
> 
> * [ ]  Task 1: Run SonarQube before and after deployment
> * [ ]  Task 2: Run OWASP ZAP before and after deployment
> * [ ]  Task 3: Run WAPITI before and after deployment
> * [ ]  Task 4: Run sqlmap before and after deployment
> * [ ]  Task 5: Run npm audit before and after deployment
> 
> **Acceptance Criteria**
> 
> * All code related configurations & vulnerabilties will patched

Unsure of whether we will do this or not since Concordia IT will not likely allow hostile attacks on their servers

**Comment by GD-Dheer** [comment]
Closing this story as some network configs will be handled in ticket #304
