### ISSUE TITLE
User Dataset Reviewal Page

### ISSUE THREAD

**Issue by GD-Dheer** [Data-Boom/SOEN490#392]
As a user, I want to be able to see all my datasets that have been flagged by an admin.

**Description** 
This epic includes mockup design, adding backend support and creating frontend UI. Currently, when an admin flags a dataset, it is supposed to go back to the user and indicate what was flagged. After the user sees this he has the option of either editing the dataset and then sending it back to the admin, deleting the dataset or approving the dataset without making any modifications to the dataset.

**Tasks**
- [x] Task 1: Create mockup design for user to review their flagged datasets
- [x] Task 2: Create Client-side UI for user dataset reviewal page
- [x] Task 3: Update backend API to support all required client requests

**Acceptance Criteria**
- User should be able to review (delete/edit/approve) their flagged datasets
