### ISSUE TITLE
[Backend] - Update CRUD API for User Flagged Datasets

### ISSUE THREAD

**Issue by GD-Dheer** [Data-Boom/SOEN490#394]
As a user, I want to be able to modify my dataset if it comes back flagged

**Description** 
Part of the backend must be updated to support user flagged dataset operations. These include getting all a user's flagged datasets, letting the user approve a dataset IFF not edited, sending dataset back to admin if edited. All operations in this ticket are for unapproved datasets ONLY

API already created: 
GET: /api/v1/userFlaggedDatasets
PUT: /api/v1/approveDataset/:datasetId

**Tasks**
- [x] Task 1: Verify above created APIs function as intended
- [x] Task 2: Create API to send a dataset back to admin if it was modified (updating the values of the unapproved dataset)
- [x] Task 3: Update DELETE: /api/v1/dataset/:datasetId to allow a user to delete a dataset only (if it their uploaded dataset uploaderID matches the dataset they are trying to delete)

**Acceptance Criteria**
- API should support the above get, put, delete type requests
