### ISSUE TITLE
[Frontend] - Create User Flagged Datasets Reviewal Page

### ISSUE THREAD

**Issue by GD-Dheer** [Data-Boom/SOEN490#395]
As a user, I want to be able to see all my datasets that were flagged.

**Description** 
This page is the implementation of mockup for user flagged datasets. This will be a new tab under user page called 'Flagged Datasets'. A user will be able to see all their flagged datasets here in a list fashion. If a dataset is clicked, it should populate in a modal. In the footer of the modal, there will be 3 buttons: 
1) Approve Dataset 
2) Delete dataset
3) Edit dataset (allowing user to change dataset values) then send it back to admin

**Tasks**
- [x] Task 1: Create a new tab under user page
- [x] Task 2: Implement list view of flagged datasets by name
- [x] Task 3: Create modal pop up of manual dataset form and after user clicks on a dataset and fill modal with dataset information
- [x] Task 4: Create footer with approve, delete, edit buttons
- [x] Task 5: Connect to backend APIs

**Acceptance Criteria**
- User should be able to see their flagged datasets and complete above operations
