### ISSUE TITLE
[Testing] Optimize UI performance by addressing Lighthouse report

### ISSUE THREAD

**Issue by JeremiahTee** [Data-Boom/SOEN490#406]
As a developer, I want to optimize the UI to accelerate page performance by addressing the debt documented in the [Lighthouse report](https://databoom.atlassian.net/wiki/spaces/DB/pages/222462117/Page+performance+testing+Lighthouse).

**Description** 
Lighthouse was run in Sprint 6 in order to benchmark the page performance on the Client side. Lighthouse suggested ways that we can accelerate the page performance, for example, by reducing unnecessary Javascript code in the Client side. 

**Additional Notes**

**Tasks**
- [ ] Run Lighthouse to generate latest report
- [ ] Address all debt reported by Lighthouse
- [ ] Run Lighthouse after addressing debt to verify optimization
- [ ] Document the optimization 

**Acceptance Criteria**
All debt reported by Lighthouse is addressed and documented.
The optimization is verified by running Lighthouse after addressing all debt, and documenting the new report.

**Comment by ds161833** [comment]
potentially sprint 9

**Comment by TiraFire** [comment]
Kept as optional
