### ISSUE TITLE
[Fronend] - Add a DOI to the dataset upload form

### ISSUE THREAD

**Issue by ds161833** [Data-Boom/SOEN490#414]
As a user, I want to be able to specify the DOI of the research paper I am referencing in my dataset

**Description** 
Backend should already support a DOI on the model, check up with Sean
Backend should already support a range of pages as a string.
Fix validation of the form to adjust required and not required fields
**Additional Notes**
some renaming should be done as part of this PR

**Tasks**
- [ ] Fix validation schema of the dataset form, to properly specify the required fields and remove required where it is not needed
- [ ] change the 'uploadDataset' route to just 'dataset'
- [ ] make the pages a string of type: 'number-number' || 'number' to support ranges of pages
- [ ] rename the files of the Dataset Upload View and DatasetUploadForm, into
- [ ] when a dataset is saved successfully display a Success message and redirect the user to the site.com/dataset/{returnedId}
- [ ] general improvements to form validations and form itself

**Acceptance Criteria**
a user can specify a doi and see their doi on created datasets

Priority High
Risks Low
