### ISSUE TITLE
[Frontend] - Auto sign out the user when the token expires

### ISSUE THREAD

**Issue by ds161833** [Data-Boom/SOEN490#415]
As a user, I want to be notified when my token is about to expire with a persistent warning snackbar specifying the time left until automatic signout. Once my token does expire I want to be automatically signed out and redirected to the login page.

**Description** 
Right now the user will just 
**Additional Notes**

**Tasks**
- [ ] display a persistent snackbar that shows how many minutes left until token expiration.
- [ ] When the token does expire sign the user out and redirect them to the login page
- [ ] **Optionally** the snackbar contains a button "signout and relogin" which signs the user out and redirects them to the login page automatically

**Acceptance Criteria**
the snackbar doesnt disappear as I go from one page to the other committing one action after the other. The snackbar displays the exact time in minutes left till token expiration starting with T-10 minutes.

Priority - HIGH
Risks - Medium
