### ISSUE TITLE
[Frontend] - Allow User to search by Variable Name

### ISSUE THREAD

**Issue by GD-Dheer** [Data-Boom/SOEN490#435]
As a user, I want to be able to search by Variable name

**Description** 
This story will allow users to select a datapoint variable name from a dropdown and then search by it. 

**Tasks**
- [x] Task 1: Fetch datapoints variable names 
- [x] Task 2: Create dropdown on dataset form to display fetched names
- [x] Task 3: Adjust frontend model to accept datapoint variable names when searching

**Acceptance Criteria**
- User should be search by Datapoints names on dataset form
