### ISSUE TITLE
[Cell Analysis] Package Cell Size Analyzer into executable

### ISSUE THREAD

**Issue by JeremiahTee** [Data-Boom/SOEN490#444]
As a user, I want to be able to install the Cell size analysis program on my machine. This program should support Mac OS, Linux and Windows to be cross-platform compatible as per request of Stakeholder. 

**Description** 
Upon investigation, we have found that the OpenCV.js API is severely limited. It would be hard to integrate into our website and could easily span two sprints. 

**Additional Notes**
This program should be tested on Mac OS, Linux and Windows systems. It packages OpenCV, Tkinter, and other libraries needed for the program to function. The user does not need to install these libraries as they are package with the executable. 
This is done using [PyInstaller](http://www.pyinstaller.org/)

**Tasks**
- [x] Package Cell Size Analyzer into executable
- [ ] Ensure that all functionalities are fully working with no issues irrespective of operating system
- [ ] Install and test the program out in Windows, Mac OS and Linux

**Acceptance Criteria**
The user is able to install the Cell size analyzer program into their machine with no issue. MacOS, Linux and Windows operating systems are supported.
The user does not need Python 

**Estimate** 2 points As we do not have prior experience to creating installers, it will take ~ 6 hours
