### ISSUE TITLE
[Cell Analysis] Ability to draw lines and estimate optimal parameters

### ISSUE THREAD

**Issue by JeremiahTee** [Data-Boom/SOEN490#446]
As a user, I want to be able to draw lines on the cells image and press a button to estimate the optimal parameters (sigma, low and high threshold) 

**Description** 
After the user has upload a cells image to the Cell Size Analyzer program, the user will draw a line on the image to denote a cell size edge. The user can then press a button to run our custom algorithm that determines the optimal parameters (sigma, low and high threshold) needed to get the best output when applying Canny edge detection algorithm.

**Additional Notes**
Drawing lines part has already been implemented in #428 . Might need optimization and modifications.
If it is not possible to estimate the optimal parameters, it is fine with our Stakeholder - as we confirmed.

**Tasks**
- [ ] Optimize/modify the current Cell size analyzer script merged into develop from #428
- [ ] Implement custom algorithm to determine optimal parameters described above
- [ ] Implement button (GUI) with Tkinter 

**Acceptance Criteria**
The user is able to draw a line on the image, press a button to determine optimal parameters for the Canny edge detection algorithm. 

**Estimate** 8 points including testing and GUI work
