### ISSUE TITLE
[Cell Analysis] Include Cell Size Analyzer executable into Cell Size Analysis page

### ISSUE THREAD

**Issue by JeremiahTee** [Data-Boom/SOEN490#449]
As a user, I want to be able to download the Cell Size Analyzer executable to install it on my machine. This executable is found at the Cell Size Analysis page with clear instructions on how to install and use it

**Description** 
The user needs to be able to download this executable from the Cell Size Analysis page.

**Additional Notes**

**Tasks**
- [ ] Include way to download .executable from Cell Size Analysis Page (Client side)
- [ ] Write and display instructions on how to install executable
- [ ] Write and display instructions on how to use the Cell Size Analyzer program

**Acceptance Criteria**
The page displays a direct link to download the executable.
The page displays clear detailed instructions on how to install and use the program.
