### ISSUE TITLE
[EPIC] - User uploaded Datasets

### ISSUE THREAD

**Issue by GD-Dheer** [Data-Boom/SOEN490#494]
As a user, I want to able to see all my uploaded datasets.

**Description** 
This epic encompasses all work required for a user to see their uploaded datasets

**Tasks**
- [ ] Task 1: Create mockup to display this page
- [ ] Task 2: Create FE based on mockup
- [ ] Task 3: Adjust backend API to support feature
- [ ] Task 4: Add system test

**Acceptance Criteria**
User should be able to see all their uploaded datasets
