### ISSUE TITLE
Home Page [References: #21]

### ISSUE THREAD

**Issue by TiraFire** [Data-Boom/SOEN490#5]
As a User, I would like to have a homepage with information on the site along with details about the menu options.

**Description**: This is the basic homepage, itll include the whats, whos, etc.

**Tasks Involved:**

- [ ] Home Page Design that is appealing and informative
   - [ ] Header with School Logo and Title
   - [ ] Access to the Page Navigation
   - [ ] Access to Sign up/Log in Pages and Log out link
   - [ ] The descriptions of the features should have links to the appropriate pages
- [ ] UI Test #21 

**Mockup Image or link to Mockup:**

![image](https://user-images.githubusercontent.com/25015601/100826700-ec233a80-3428-11eb-9b4c-07e5e1e8bc65.png)

**Acceptance Criteria**
- Descriptive details on each of the menu options
- Concordia Logo
- Name or Logo of the website
- Access to Navigation
- Access to Sign up/Log in pages and Log out link

**Story Point** - 2
**Risk** - Low
**Priority** - High
