### ISSUE TITLE
[Frontend] - Query & Display Available data sets on the Search Page

### ISSUE THREAD

**Issue by ds161833** [Data-Boom/SOEN490#51]
As a user, I would like to query a dataset based on a specific filter on the search page in order to be able to view or download the resulting queries.

**Acceptance Criteria:**

The Categories and Subcategories must have the ability to have multiple selection for the user to specify a custom search. 
The user should be able:
-  specify the temperature by different ranges. 
- search by material (category) 
   - material displays Oxidizer, Fuel, Dilutent results pertaining to material
- Year (range)
- Author (array of multiple authors)
- OutputFormat (array of multiple formats) ->  txt/CSV,excel, XML, HDF5, and JSON

A toggle for case enforcing case sensitivity should be available:
- IsCaseSensitive toggle

**Description:**
The user will be able to query a dataset based on specific filters that were specified. The dataset query result is displayed in a neat form to the user on the same Search page. Additionally, the user is able to download this dataset information. 
**Note**: This user story initially only deals with serving the front-end: the layout and styling implementation.
Once the backend endpoint is set-up, the connection can be made. Dependency on #116 

**Tasks Involved:**

- [ ] Setup the appropriate forms and textbox inputs
- [ ] Setup the appropriate tables in their correct format
- [ ] Connect the back-end with the front-end. Dependent on #116 

**Mockup Image or link:**

![image](https://user-images.githubusercontent.com/25015601/96743805-5ceb2780-1392-11eb-8231-b360b6c8914a.png)

**Risk** - High
**Priority** - High

**Comment by GD-Dheer** [comment]
> We need a page that displays all the data sets available on the database

Can we get more information on what exactly this is supposed to be? I don't what this page is supposed to render as content. It could turn out to be a massive page... @TiraFire @Mehrdadmaskull @ds161833

**Comment by TiraFire** [comment]
> > We need a page that displays all the data sets available on the database
> 
> Can we get more information on what exactly this is supposed to be? I don't what this page is supposed to render as content. It could turn out to be a massive page... @TiraFire @Mehrdadmaskull @ds161833

Changed the description to a more concrete example, let me know if it is correct.
