### ISSUE TITLE
[Backend] - Implement a search dataset endpoint

### ISSUE THREAD

**Issue by Mehrdadmaskull** [Data-Boom/SOEN490#53]
As a developer, I would like send a query consisting of the year of the dataset, category (cell size, minimum tube), subcategory (width, height, etc., "round, confined"), dataset fuel, oxidizer, author, dilutent etc.

Query parameters should be specified either in the body of URL of the GET request

https://stackoverflow.com/questions/4024271/rest-api-best-practices-where-to-put-parameters
    oxidizer: '',
    year: '',
    categories: '',
    subcategories: '',
    fuel: '',
    author: '',
    dilutent: '',

Also, include ignored case search

**Tasks Involved:**

- [x] Creating an endpoint accessible from frontend
- [x] Design queries that can be executed against the datasets
- [x] Implement queries
- [x] also accept an array of ids to return

**Acceptance Criteria:**
Should send a GET requests to a localhost:4000/datasets and retrieve found datasets back in .json format .

**Risk** - High
**Priority** - High

**Comment by GD-Dheer** [comment]
> Querying the database and showing the current entries from the db on a page for the user to select and display.
> 
> **Note**: Displaying is not part of this story.

This story should be refactored a little on the service/model side, the logic was done quickly and was not setup in an optimal manner, for example: getConnection for example is called with every model request.

**Comment by silent-po2** [comment]
As noted in pull-request#153, the code and functionality for this issue is all complete, but requires unit tests.

**Comment by silent-po2** [comment]
Frontend devs have requested the ability to pass an array of data set IDs as a search parameter. This will be added shortly.
