### ISSUE TITLE
About Page [References: #24]

### ISSUE THREAD

**Issue by TiraFire** [Data-Boom/SOEN490#6]
As a User, I would like to have an About Page with information about the legalities, licenses, and other important information.

**Description**: This is the basic About Page, will include the contact information, licenses, access to developers linkedins, description of the project and stakeholder.

**Tasks Involved:**

- [ ] About Page Design that is appealing and informative
   - [ ] Section about contact information
   - [ ] Section about the develops including links to their linkedins
   - [ ] Licenses and legal information
   - [ ] Section concerning information about the stakeholder
   - [ ] Section with a detailed account of the project and reasons behind it
   - [ ] Credit to the Caltech Site
- [ ] UI Test #24  

**Mockup Image or link to Mockup:**

![image](https://user-images.githubusercontent.com/25015601/100827585-137b0700-342b-11eb-9756-5b31e35b1bfc.png)

**Acceptance Criteria**
- Descriptive detail of each of the tasks above (approved by stakeholder)

**Story Point** - 2
**Risk** - Low
**Priority** - Low
