### ISSUE TITLE
[Operations] Deployment

### ISSUE THREAD

**Issue by Mehrdadmaskull** [Data-Boom/SOEN490#70]
As a user, I want the application to be assessable over the web

**Description** 
This EPIC includes the full deployment of the application. It includes updating our application configurations to be production ready, setting up the host server, then deploying our frontend & backend.

**Tasks**
- [ ] Task 1: Install nodejs, react on Kiyanda server with correct prod dependencies
- [ ] Task 2: Migrate database
- [ ] Task 3: Run sonar/security tools before beginning code migration to patch any security flaws
- [ ] Task 4: Migrate Frontend Client to be hosted on Concordia Server
- [ ] Task 5: Migrate Backend API to be hosted on Concordia Server

Good start: https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-18-04

**Acceptance Criteria**
- Application is accessible from the web
