### ISSUE TITLE
[Frontend] Set up Graph Page and its appropriate Components

### ISSUE THREAD

**Issue by Mehrdadmaskull** [Data-Boom/SOEN490#77]
As a user, I would like to interact with the Graph on the graph page in order to be able to search and view custom datasets, and also export any resulting graph. 

**Tasks Involved**:
- [x]   Graph component from Epic #66  Refer to specific mockup in #66
- [x]   Search component from Epic #128 Refer to specific mockup in #128
- [x]  Ability to export (download) the current data set associated with its corresponding graph (formats: .csv, .xls, .xlsx, .txt, .xml, .hdf5) #127 
- [x]  Ability to export a snapshot of the Graph as a .png file. 

Mockup Image for the Search & Graph component
![image](https://user-images.githubusercontent.com/6520150/99210184-23d88400-2793-11eb-89d0-68f69d672709.png)

_Export mockup (to be added)_

**Acceptance Criteria**
User should be able to fully interact with the Graph component. The search component will also be available to the user for specifying custom filters. Based on the resulting query from the user specified filters, the graph is updated accordingly.
Finally, the user is able to export corresponding dataset matching the graph as a .json file (for now). Future implementation will support the rest of the formats. (Same format as the upload json file)

Link to JSON template which includes all the necessary fields for the form (JsonSample.json) : https://drive.google.com/drive/folders/1JWyLKra_hNhUOp19ioMeHPkk8Mxnf-8N

**Risk** - Low
**Priority** - Med

**Developer notes**
- Connect to the backend API to receive the ViewModel
- The webpage will have a container for the Graph which serves the UI to request data from backend
- The dataset object is queried from the database

**Comment by GD-Dheer** [comment]
> We need to have a webpage that has a container for the graph and provides the UI to request data from backend.
> The dataset object should be queried from the database.
> 
> **Acceptance Criteria:**
> 
> * Connect to the backend API to receive the viewmodel

To finish the graphing completely this sprint, this story should add an input option for the user to specify which dataset the user is looking for
